# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 
  config.vm.box = "ubuntu/trusty64"
  
  # Use private network
  config.vm.network "private_network", ip: "192.168.100.42"
  
  # Map host 2222 to guest 2222, port used by Docker SFTP
  config.vm.network "forwarded_port", guest: 2222, host: 2222

  # Define memory
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  # Mount shared resources
  config.vm.synced_folder "../ssh/", "/vagrant/ssh", create:true
  config.vm.synced_folder "../files/", "/vagrant/files", create:true
  
  config.vm.provision "docker" do |d|
    
	# Pull required Docker images
	d.pull_images "atmoz/sftp" # SFTP with OpenSSH for SftpHelper and SshHelper
	
	#
	# Launch required Docker containers
	#
	
	# SFTP container, with user 'quark' and password 'password' and port 2222
	d.run "atmoz/sftp",
      cmd: "quark:password",
      args: "-p 2222:22  \
	  -v /vagrant/ssh/id_rsa.pub:/home/quark/.ssh/keys/id_rsa.pub:ro \
	  -v /vagrant/files:/home/quark/files:rw"
  end
  
  config.vm.provision "docker" do |d|
    
  end
  
  

end
