# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 
  config.vm.box = "ubuntu/trusty64"
  
  # Use private network
  config.vm.network "private_network", ip: "192.168.100.42"

  # Define memory
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  config.vm.provision "docker" do |d|
    
	# Pull required Docker images
	d.pull_images "atmoz/sftp" # SFTP with OpenSSH for SftpHelper and SshHelper
	
	#
	# Launch required Docker containers
	#
	
	# SFTP container, with user 'quark' and password 'password'
	d.run "atmoz/sftp",
      cmd: "quark:password",
      args: "-p 2222:22"
  end
  
  config.vm.provision "docker" do |d|
    
  end
  
  

end
